FROM node:18

ENV PNPM_HOME=/usr/local/share/pnpm
ENV PATH=$PNPM_HOME:$PATH
RUN corepack enable && corepack prepare pnpm@9.12.0 --activate

WORKDIR /app
# layer cache for deps
COPY package.json pnpm-workspace.yaml ./
COPY services/api/package.json services/api/package.json
RUN pnpm install

# app sources
COPY . .

WORKDIR /app/services/api
EXPOSE 3000
CMD ["pnpm","dev"]